trigger: none

schedules:
  - cron: "0 3 * * *"
    displayName: Run E2E tests daily
    branches:
      include:
      - main

pr: none

variables:
  - group: AtlasEndToEndTests

jobs: 
- job: Run_Tests
  pool:
    vmImage: 'windows-latest'
  steps:
    - task: FileTransform@2
      displayName: 'Set environment variables'
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)'
        xmlTransformationRules: '' # Prevents task error: "Unable to apply transformation for the given package - Changes are already present in the package."
        jsonTargetFiles: '**/appsettings.json'
      continueOnError: false

    - task: DotNetCoreCLI@2
      displayName: 'Nuget Restore'
      inputs:
        command: 'restore'
        feedsToUse: 'config'
        nugetConfigPath: '$(System.DefaultWorkingDirectory)/nuget.config'
    
    - task: DotNetCoreCLI@2
      displayName: 'Run Atlas.Auto.Tests'
      inputs:
        command: test
        projects: '$(System.DefaultWorkingDirectory)/Atlas.Auto.Tests/Atlas.Auto.Tests.csproj'
        arguments: '--no-restore -v d'