# Set trigger as required for the target Atlas environment
trigger: none
pr: none

jobs: 
- job: Run_Tests
  pool:
    vmImage: 'windows-latest'
  steps:
    - task: FileTransform@2
      # Pipeline must have variables that match those in appsettings.json.
      # Use `.` to retrieve nested values, e.g., var name `DonorImport.ApiKey` would be used to fetch setting:`{ "DonorImport": { "ApiKey": "value" } }`
      displayName: 'Set environment variables'
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)'
        xmlTransformationRules: '' # Prevents task error: "Unable to apply transformation for the given package - Changes are already present in the package."
        jsonTargetFiles: '**/appsettings.json'
      continueOnError: false

    - task: DotNetCoreCLI@2
      displayName: 'Nuget Restore'
      inputs:
        command: 'restore'
        feedsToUse: 'config'
        nugetConfigPath: '$(System.DefaultWorkingDirectory)/nuget.config'
    
    - task: DotNetCoreCLI@2
      displayName: 'Run Atlas.Auto.Tests'
      inputs:
        command: test
        projects: '$(System.DefaultWorkingDirectory)/Atlas.Auto.Tests/Atlas.Auto.Tests.csproj'
        arguments: '--no-restore -v d'