# Set trigger as required for the target Atlas environment
trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
  
stages: 
- stage: build
  displayName: "Build"
  jobs:
  - job:
    displayName: 'Restore Cache and Build'
    steps: 
      - task: UseDotNet@2
        displayName: 'Install .NET Core SDK'
        inputs:
          packageType: 'sdk'
          version: 8.0.x

      - task: Cache@2
        displayName: Cache
        inputs:
          key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
          restoreKeys: |
            nuget | "$(Agent.OS)"
            nuget
          path: '$(NUGET_PACKAGES)'
          cacheHitVar: 'CACHE_RESTORED'

      - task: DotNetCoreCLI@2
        displayName: 'Restore'
        condition: ne(variables.CACHE_RESTORED, true)
        inputs:
          command: 'restore'
          projects: "**/Atlas.Auto.Tests.csproj"
          feedsToUse: 'config'
          nugetConfigPath: 'nuget.config'
          
      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: 'build'
          projects: '**/Atlas.Auto.Tests.csproj'
          arguments: '--configuration $(buildConfiguration)'

      - task: CopyFiles@2
        displayName: 'Copy Test artifacts for later use in the pipeline'
        inputs:
          contents: 'Atlas.Auto.Tests/bin/Release/net8.0/**'
          targetFolder: '$(Build.ArtifactStagingDirectory)'

      - publish: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Publish Test artifacts for later use in the pipeline'
        artifact: dropTestSuite
        
- stage: runTests
  displayName: "Run Tests"
  jobs:
  - template: azure-test-run-template.yml
    parameters:
      testCategoryJobs:
      - job: HealthCheck
